export enum Role {
  dev = 'dev',
  devops = 'devops',
  teamLead = "teamLead",
  teckLead = 'teckLead',
  groupLead = 'groupLead',
  cto = "cto",
  rh = 'rh',
  po = 'po',
  scrum = 'scrum',
  marketing = 'marketing',
  admin = 'admin',
  sales = 'sales',
  design = 'design',
}
